from __future__ import annotations

import os
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = PROJECT_ROOT / "src"
DATA_DIR = Path(os.getenv("FITNESS_DATA_DIR", str(PROJECT_ROOT / "data"))).expanduser()
RAW_DIR = Path(os.getenv("FITNESS_RAW_DIR", str(DATA_DIR / "raw"))).expanduser()
INTERIM_DIR = Path(os.getenv("FITNESS_INTERIM_DIR", str(DATA_DIR / "interim"))).expanduser()
PROCESSED_DIR = Path(os.getenv("FITNESS_PROCESSED_DIR", str(DATA_DIR / "processed"))).expanduser()
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
LOGS_DIR = PROJECT_ROOT / "logs"
DB_PATH = Path(os.getenv("FITNESS_DB_PATH", str(DATA_DIR / "fitness_part1.sqlite"))).expanduser()
CHECKPOINTS_DIR = Path(os.getenv("FITNESS_CHECKPOINTS_DIR", str(INTERIM_DIR / "checkpoints"))).expanduser()
APP_CACHE_PATH = Path(os.getenv("FITNESS_APP_CACHE_PATH", str(PROCESSED_DIR / "app_cache.json"))).expanduser()

APP_TITLE = "r/fitness NLP Explorer"
SUBREDDIT = "fitness"
TARGET_TOPIC_COUNT = 8
MIN_TOPIC_COUNT = 5
MAX_TOPIC_COUNT = 20
TOPIC_MODEL_TOTAL_DOC_TARGET = int(os.getenv("TOPIC_MODEL_TOTAL_DOC_TARGET", "15000"))
TOPIC_MODEL_MIN_COMMENT_SHARE = float(os.getenv("TOPIC_MODEL_MIN_COMMENT_SHARE", "0.30"))
TOP_LEVEL_COMMENTS_PER_POST = int(os.getenv("TOP_LEVEL_COMMENTS_PER_POST", "3"))
TOPIC_MODEL_RANDOM_SEED = int(os.getenv("TOPIC_MODEL_RANDOM_SEED", "42"))
TOPIC_REPRESENTATIVE_DOCS = int(os.getenv("TOPIC_REPRESENTATIVE_DOCS", "5"))
MIN_POST_TEXT_CHARS = int(os.getenv("MIN_POST_TEXT_CHARS", "20"))
MIN_COMMENT_TEXT_CHARS = int(os.getenv("MIN_COMMENT_TEXT_CHARS", "40"))
MIN_COMMENT_TOKEN_COUNT = int(os.getenv("MIN_COMMENT_TOKEN_COUNT", "8"))
STANCE_TOPIC_SHARE_THRESHOLD = float(os.getenv("STANCE_TOPIC_SHARE_THRESHOLD", "0.03"))
STANCE_INCLUDE_OPTIONAL_TOPIC_0 = os.getenv("STANCE_INCLUDE_OPTIONAL_TOPIC_0", "0") == "1"
STANCE_MIN_TOPIC_COMMENTS = int(os.getenv("STANCE_MIN_TOPIC_COMMENTS", "40"))
STANCE_MIN_MINORITY_COMMENTS = int(os.getenv("STANCE_MIN_MINORITY_COMMENTS", "12"))
STANCE_MIN_MINORITY_SHARE = float(os.getenv("STANCE_MIN_MINORITY_SHARE", "0.18"))
STANCE_MIN_SILHOUETTE = float(os.getenv("STANCE_MIN_SILHOUETTE", "0.02"))
STANCE_MAX_CENTROID_SIMILARITY = float(os.getenv("STANCE_MAX_CENTROID_SIMILARITY", "0.92"))
MIN_POSTS_REQUIRED = 15_000
MIN_MONTH_SPAN_REQUIRED = 6
ARCTIC_SHIFT_BASE_URL = os.getenv(
    "ARCTIC_SHIFT_BASE_URL",
    "https://arctic-shift.photon-reddit.com",
)
ARCTIC_SHIFT_TIMEOUT_SECONDS = int(os.getenv("ARCTIC_SHIFT_TIMEOUT_SECONDS", "60"))
ARCTIC_SHIFT_PAGE_SIZE = int(os.getenv("ARCTIC_SHIFT_PAGE_SIZE", "100"))
ARCTIC_SHIFT_USER_AGENT = os.getenv(
    "ARCTIC_SHIFT_USER_AGENT",
    "fitness-nlp-project/0.1 (academic project ingestion)",
)
INGESTION_FIELDS = (
    "id",
    "author",
    "title",
    "selftext",
    "created_utc",
    "score",
    "num_comments",
    "permalink",
    "url",
    "removed_by_category",
    "removed_by",
    "author_fullname",
)
MAX_WINDOW_SCAN_MONTHS = int(os.getenv("MAX_WINDOW_SCAN_MONTHS", "60"))
WINDOW_START_UTC = os.getenv("WINDOW_START_UTC")
WINDOW_END_UTC = os.getenv("WINDOW_END_UTC")

PIPELINE_STAGES = (
    "ingest_posts",
    "ingest_comments",
    "prepare_features",
    "fit_topics",
    "fit_stance",
    "build_app_cache",
)

METHODS_NOTES = [
    "Arctic Shift is used for acquisition because PRAW is unavailable for this project setup.",
    "SQLite is the primary store for posts, comments, authors, topic outputs, and Part 2-compatible document metadata.",
    "r/fitness is megathread-driven, so topic discovery uses a hybrid corpus of all eligible posts plus a bounded sample of eligible top-level comments.",
    "Topic modeling targets 8 interpretable topics, while enforcing a final displayed topic count between 5 and 20.",
    "Topic labels receive a light manual review pass only when autogenerated labels are misleading.",
    "Hybrid topic prevalence and time series are computed over modeled documents, even when stored in legacy post-named schema fields for Part 2 compatibility.",
    "Trending vs persistent labels are computed from monthly topic share over the selected 6+ month window.",
    "Stance detection is unsupervised and can over-separate near-consensus topics; weak or overlapping splits are explicitly flagged.",
    "Feature preparation excludes deleted, removed, bot-authored, and ultra-short texts from modeling while preserving them in corpus-level counts.",
    "When comparing topic prevalence across eras, absence of a topic in one era may reflect under-sampling rather than genuine topical non-existence.",
]

VALIDATED_STANCE_TOPIC_IDS = (1, 2, 5)
OPTIONAL_STANCE_TOPIC_IDS = (0,)
EXCLUDED_STANCE_TOPIC_IDS = (3, 4, 6, 7)


def ensure_directories() -> None:
    for path in (DATA_DIR, RAW_DIR, INTERIM_DIR, PROCESSED_DIR, ARTIFACTS_DIR, LOGS_DIR, CHECKPOINTS_DIR):
        path.mkdir(parents=True, exist_ok=True)


def checkpoint_path(stage_name: str) -> Path:
    return CHECKPOINTS_DIR / f"{stage_name}.json"
